name: Publish Staging

on:
  push:
  #  branches:
  #   - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: codebuddies/backend/cb-backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          workdir: cbv3_django_prototype
          tag_names: true

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
          transient: true
          desc: Setting up staging deployment for ${{ steps.publish.outputs.tag }}

      - name: checkout
        uses: actions/checkout@master

      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_STAGING_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          port: ${{ secrets.DO_STAGING_SSH_PORT }}
          username: root
          source: "docker-compose-prod.yaml,nginx/app.conf"
          target: "./"

      - name: stop existing deployment
        uses: appleboy/ssh-action@master
        env:
          DO_STAGING_DB_USER: ${{ secrets.DO_STAGING_DB_USER }}
          DO_STAGING_DB_PASSWORD: ${{ secrets.DO_STAGING_DB_PASSWORD }}
          DO_STAGING_DB_HOST: ${{ secrets.DO_STAGING_DB_HOST }}
          DO_STAGING_DB_PORT: ${{ secrets.DO_STAGING_DB_PORT }}
          DO_STAGING_DB_NAME: ${{ secrets.DO_STAGING_DB_NAME }}
          CB_IMAGE_TAG: ${{ steps.publish.output.tag }}
        with:
          host: ${{ secrets.DO_STAGING_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          port: ${{ secrets.DO_STAGING_SSH_PORT }}
          username: root
          script: |
            export STAGING_DB_URL="postgres://$DO_STAGING_DB_USER:$DO_STAGING_DB_PASSWORD@$DO_STAGING_DB_HOST:$DO_STAGING_DB_PORT/$DO_STAGING_DB_NAME"
            docker-compose -f docker-compose-prod.yaml down

      - name: start new deployment
        uses: appleboy/ssh-action@master
        env:
          DO_STAGING_DB_USER: ${{ secrets.DO_STAGING_DB_USER }}
          DO_STAGING_DB_PASSWORD: ${{ secrets.DO_STAGING_DB_PASSWORD }}
          DO_STAGING_DB_HOST: ${{ secrets.DO_STAGING_DB_HOST }}
          DO_STAGING_DB_PORT: ${{ secrets.DO_STAGING_DB_PORT }}
          DO_STAGING_DB_NAME: ${{ secrets.DO_STAGING_DB_NAME }}
          CB_IMAGE_TAG: ${{ steps.publish.output.tag }}
        with:
          host: ${{ secrets.DO_STAGING_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          port: ${{ secrets.DO_STAGING_SSH_PORT }}
          username: root
          script: |
            export STAGING_DB_URL="postgres://$DO_STAGING_DB_USER:$DO_STAGING_DB_PASSWORD@$DO_STAGING_DB_HOST:$DO_STAGING_DB_PORT/$DO_STAGING_DB_NAME"
            docker-compose -f docker-compose-prod.yaml up

      - name: finish deployment
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: https://stage-api.codebuddies.org
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
